### ISSUE TITLE
麻烦问个协议的问题。

### ISSUE THREAD

**Issue by swituo** [zephyrzoom/douyu#1]
data.writeInt32LE(msg.length + 9, 0);
 data.writeInt32LE(msg.length + 9, 4);
为什么要+9个字节？

消息长度:4 字节小端整数,表示整条消息(包括自身)长度(字节数)。
消息长度出现两遍,二者相同。

整条消息的长度不应该是13个字节么？

谢谢。

**Comment by zephyrzoom** [comment]
![screenshot from 2017-08-12 19-52-09](https://user-images.githubusercontent.com/3319755/29240456-6754eabc-7f98-11e7-8393-8ff3a5f04839.png)

**Comment by zephyrzoom** [comment]
我又看了下上面的图画错了，好久没看有点懵逼0.0
![screenshot from 2017-08-13 00-26-00](https://user-images.githubusercontent.com/3319755/29242378-dd25f3f0-7fbe-11e7-9e1a-6c391930b6cc.png)

**Comment by swituo** [comment]
不好意思，+9我知道是正确的，因为+13无法得到receive。
但因为一直得不到消息，所以找代码参考…… 我觉得理解不了文档…… 
文档说整条消息的长度包括自己，二条都是（这句应该表明长度也是消息内容），这几个条件应该是：4字节长度+4字节长度+2字节消息类型+0+0+消息长度+结尾……
所以就有疑问，为什么你们当时会想到9个字节的…… = =

**Comment by zephyrzoom** [comment]
那是因为之前没有公开协议的时候是自己抓包分析的，基本知道每个字段大小，只是不知道含义。

**Comment by swituo** [comment]
嗯, 谢谢.
